language: node_js

node_js:
  - "8"

env:
  matrix:
    - TEST_TYPE=ci
git:
  submodules:
    false

addons:
  apt:
    packages:
      - xvfb

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install

script:
  - |
    if [ "$TEST_TYPE" = ci ]; then
      npm run karma start libs/karma.conf.js
    fi
